<style scoped>
    /* Generated by http://css.spritegen.com CSS Sprite Generator */
    
    .bank-icon-ceb, .bank-icon-pab, .bank-icon-ljb, .bank-icon-abc, .bank-icon-bcm, 
    .bank-icon-bob, .bank-icon-boc, .bank-icon-bosh, .bank-icon-ccb, .bank-icon-cib, 
    .bank-icon-citic, .bank-icon-cmb, .bank-icon-cmbc, .bank-icon-czb, .bank-icon-fail, 
    .bank-icon-gdb, .bank-icon-hxb, .bank-icon-icbc, .bank-icon-psbc, .bank-icon-spdb
    { display: inline-block; background: url('./images/bank-icon.png') no-repeat; overflow: hidden; text-indent: -9999px; text-align: left; }
    
    .bank-icon-ceb { background-position: -2px -0px; width: 68px; height: 68px; }
    .bank-icon-pab { background-position: -2px -70px; width: 67px; height: 67px; }
    .bank-icon-ljb { background-position: -2px -139px; width: 64px; height: 64px; }
    .bank-icon-abc { background-position: -2px -205px; width: 60px; height: 60px; }
    .bank-icon-bcm { background-position: -2px -267px; width: 60px; height: 60px; }
    .bank-icon-bob { background-position: -2px -329px; width: 60px; height: 60px; }
    .bank-icon-boc { background-position: -2px -391px; width: 60px; height: 60px; }
    .bank-icon-bosh { background-position: -2px -453px; width: 60px; height: 60px; }
    .bank-icon-ccb { background-position: -2px -515px; width: 60px; height: 60px; }
    .bank-icon-cib { background-position: -2px -577px; width: 60px; height: 60px; }
    .bank-icon-citic { background-position: -2px -639px; width: 60px; height: 60px; }
    .bank-icon-cmb { background-position: -2px -701px; width: 60px; height: 60px; }
    .bank-icon-cmbc { background-position: -2px -763px; width: 60px; height: 60px; }
    .bank-icon-czb { background-position: -2px -825px; width: 60px; height: 60px; }
    .bank-icon-fail { background-position: -2px -887px; width: 60px; height: 60px; }
    .bank-icon-gdb { background-position: -2px -949px; width: 60px; height: 60px; }
    .bank-icon-hxb { background-position: -2px -1011px; width: 60px; height: 58px; }
    .bank-icon-icbc { background-position: -2px -1071px; width: 60px; height: 60px; }
    .bank-icon-psbc { background-position: -2px -1133px; width: 60px; height: 60px; }
    .bank-icon-spdb { background-position: -2px -1195px; width: 60px; height: 60px; }

    .bank-icon{
        opacity: 1;
        font-size: 24px;
        vertical-align: middle;
    }
    .bank-icon.active{
        opacity: .7;
    }
</style>

<template>
    <span :class="getCssCls()" :style="style" v-tap="tap"></span>
</template>

<script>
	import $ from 'tethys';
    import Vue from 'vue';
    import vueTap from 'v-tap';

    Vue.use(vueTap);

    export default {
        props: {
            // 按钮类型，可为空或submit
            'type': {
                default: ''
            },
            // 自定义样式，作用于组件的容器上
            'style': String,
            // 自定义class，作用于组件的容器上
            'class': String,
        },
        data: function(){
            return {
                // 是否按下状态
                active: false
            };
        },
        methods: {
            // 动态计算按钮的 class
            getCssCls: function(){
                var cls = [ 'bank-icon' ];

                // 按钮type的class
                if(this.type) cls.push('bank-icon-' + this.type.toLowerCase());

                // active时的class
                if(this.active) cls.push('active');
                
                // 传入的自定义class
                if(this['class']) cls.push(this['class']);
                
                return cls.join(' ');
            },
            // 触发点击事件
            tap: function(){
                this.$emit('tap');
            },
        },
		ready: function(){
            var vm = this;

            // 按下按钮/放开按钮时，改变active状态
			$(this.$el).on('touchstart, mousedown', function(e){
				vm.active = true;
			});

			$(document.body).on('touchend, mouseup', function(e){
				vm.active = false;
			});
        }
    }
</script>